/* GENERATED by scripts/ohms/build-index.mjs — do not edit by hand.
 * Re-run `npm run ohms:index` after changing anything in public/ohms/.
 *
 * The indexed segments of every OHMS export, keyed by the `ohmsXml` path as it
 * appears on each record in `interviews.ts`. `time` is integer seconds from the
 * start of the recording.
 *
 * Two exports (Berman 1a/1b) publish no index yet and carry an empty list —
 * consumers must handle a recording with no segments.
 *
 * Read this through `src/lib/ohms-highlights.ts` rather than directly: segment
 * titles include administrative markers ("Introduction", "Technical
 * Difficulties") that should not be presented as topics.
 */

export type OhmsIndexSegment = {
  /** Segment start, in integer seconds. Not necessarily 0 for the first one. */
  time: number;
  title: string;
  /** OHMS's translated title. Empty in every current export. */
  titleAlt: string;
};

export type OhmsIndexEntry = {
  /** The export's OHMS record id, e.g. "interview36980". */
  id: string;
  segmentCount: number;
  segments: OhmsIndexSegment[];
};

export const ohmsIndex: Record<string, OhmsIndexEntry> = {
  "/ohms/interview36980.xml": {
    id: "interview36980",
    segmentCount: 10,
    segments: [
      { time: 0, title: "The Rivalry Between Ngô Đình Nhu and Ngô Đình Cẩn", titleAlt: "" },
      { time: 590, title: "Labor Unions", titleAlt: "" },
      { time: 887, title: "Dr. Trần Kim Tuyến's Role in 1950s South Vietnamese Politics", titleAlt: "" },
      { time: 1434, title: "Lê Khắc Duyệt's Role in 1950s South Vietnamese Politics", titleAlt: "" },
      { time: 1863, title: "The 1960 Coup Attempt and Ngô Đình Cẩn's Foresight", titleAlt: "" },
      { time: 2562, title: "Ngô Đình Cẩn and the Ngô Brothers' Dynamics in the 1950s", titleAlt: "" },
      { time: 3046, title: "The Regime's Decline", titleAlt: "" },
      { time: 3525, title: "Bến Cát Intelligence Operation", titleAlt: "" },
      { time: 4284, title: "The 1963 Buddhist Crisis", titleAlt: "" },
      { time: 5081, title: "Ngô Đình Cẩn's Trial and Death", titleAlt: "" },
    ],
  },
  "/ohms/interview36981.xml": {
    id: "interview36981",
    segmentCount: 8,
    segments: [
      { time: 0, title: "Greetings and Light Conversations", titleAlt: "" },
      { time: 324, title: "American Ideology, Foreign Intervention, and Vietnamese Resistance in early Vietnam War", titleAlt: "" },
      { time: 731, title: "The Vietnam War v.s. Previous 20th Century Conflicts", titleAlt: "" },
      { time: 1027, title: "Post–Cold War U.S. Interventions, Oil Politics, and the Use of Pretexts", titleAlt: "" },
      { time: 1559, title: "Vietnam and the US in the Cold War Context", titleAlt: "" },
      { time: 2334, title: "Scholarship on the Vietnam War", titleAlt: "" },
      { time: 2570, title: "Vietnam's Adjustment to State-Controlled Market Economy", titleAlt: "" },
      { time: 3108, title: "Reflections on War and Peace in Vietnam and Asia", titleAlt: "" },
    ],
  },
  "/ohms/interview36982.xml": {
    id: "interview36982",
    segmentCount: 11,
    segments: [
      { time: 1, title: "Start of discussion, literature and general reflections on the war", titleAlt: "" },
      { time: 300, title: "Pause in Interview, Visuals of books", titleAlt: "" },
      { time: 571, title: "American Lessons Learned about the War/ What was the war about?", titleAlt: "" },
      { time: 946, title: "Vietnamese Nationalism, Ideologies, and Explanations for the War and U.S. Defeat", titleAlt: "" },
      { time: 1370, title: "Discussion about Alexis de Tocqueville", titleAlt: "" },
      { time: 1630, title: "From America’s Anti-Communism/Reasons for Involvement to China’s Political Power Structure", titleAlt: "" },
      { time: 1846, title: "Vietnamese Socialism, Free Markets, and the New Generation", titleAlt: "" },
      { time: 2081, title: "Friendliness After War, Historical Memory, and Underlying Tensions", titleAlt: "" },
      { time: 2240, title: "Discussion on memory, legacy of war and the books about the war", titleAlt: "" },
      { time: 2480, title: "Phạm Xuân Ẩn life philosophy and thoughts on fate", titleAlt: "" },
      { time: 3042, title: "Phạm Xuân Ẩn Library and closing thoughts", titleAlt: "" },
    ],
  },
  "/ohms/interview41608.xml": {
    id: "interview41608",
    segmentCount: 0,
    segments: [

    ],
  },
  "/ohms/interview41609.xml": {
    id: "interview41609",
    segmentCount: 0,
    segments: [

    ],
  },
  "/ohms/interview41646.xml": {
    id: "interview41646",
    segmentCount: 13,
    segments: [
      { time: 0, title: "Introduction", titleAlt: "" },
      { time: 24, title: "Family History and Childhood", titleAlt: "" },
      { time: 406, title: "Time at the Seattle World's Fair and First Exposure to Dartmouth", titleAlt: "" },
      { time: 597, title: "Arrival at Dartmouth and Student Life", titleAlt: "" },
      { time: 1018, title: "Switch from English Major to Spanish and Latin American Literature", titleAlt: "" },
      { time: 1269, title: "Passion for Spanish Literature from Childhood Ethical Tension", titleAlt: "" },
      { time: 1517, title: "Switch to International Relations Major", titleAlt: "" },
      { time: 1683, title: "The Summer of Sophomore Year and Introduction to Chinese at Dartmouth", titleAlt: "" },
      { time: 2008, title: "Chinese class at Dartmouth / Decision to go to Taiwan", titleAlt: "" },
      { time: 2430, title: "Life in Taiwan and Move to Vietnam", titleAlt: "" },
      { time: 2821, title: "Journey to Taiwan and Experience of Authoritarian Rule Under Chiang Kai-shek", titleAlt: "" },
      { time: 3301, title: "Family reaction to Morrow's time in Asia and his Mother's recovery.", titleAlt: "" },
      { time: 3835, title: "Reflection on his Father's Influence", titleAlt: "" },
    ],
  },
  "/ohms/interview42105.xml": {
    id: "interview42105",
    segmentCount: 10,
    segments: [
      { time: 0, title: "Arrival in Vietnam", titleAlt: "" },
      { time: 818, title: "Life in Cholon and Encounter with Violence", titleAlt: "" },
      { time: 1386, title: "Experience at the Mekong Delta Base", titleAlt: "" },
      { time: 2538, title: "The TiTi Canal Ambush", titleAlt: "" },
      { time: 3225, title: "Building Credibility and the Origins of Dispatch News Service", titleAlt: "" },
      { time: 3764, title: "Tet Offensive and the Battle of Hue", titleAlt: "" },
      { time: 5020, title: "Publishing about My Lai", titleAlt: "" },
      { time: 5686, title: "Draft Resistance and FBI Pursuit of Morrow's Family", titleAlt: "" },
      { time: 6677, title: "Investigating the CIA's Secret War", titleAlt: "" },
      { time: 7605, title: "Undercover in Thailand and Infiltrating the Seventh Air Force", titleAlt: "" },
    ],
  },
  "/ohms/interview42197.xml": {
    id: "interview42197",
    segmentCount: 7,
    segments: [
      { time: 0, title: "Decision to Report Highway 1", titleAlt: "" },
      { time: 660, title: "Massacre on Highway 1 and Capture", titleAlt: "" },
      { time: 1540, title: "Identification as High-Value Prisoners and Transfer to Khmer Guards", titleAlt: "" },
      { time: 2383, title: "Intervention by Senior Officer and Establishment of Controlled Captivity", titleAlt: "" },
      { time: 2931, title: "American Rescue Attempt", titleAlt: "" },
      { time: 4009, title: "Diplomatic Backchannels and Phạm Xuân Ẩn", titleAlt: "" },
      { time: 6300, title: "Morgenthau, Realism, and Reassessment of the War", titleAlt: "" },
    ],
  },
  "/ohms/interview42211.xml": {
    id: "interview42211",
    segmentCount: 20,
    segments: [
      { time: 0, title: "Dartmouth Mentorship and Returning from Cambodian Captivity", titleAlt: "" },
      { time: 301, title: "Laos as a Neutral State and Hidden Theater of War", titleAlt: "" },
      { time: 999, title: "Intellectual Curiosity and Southeast Asia as an Unformed Field", titleAlt: "" },
      { time: 1341, title: "Vietnam War Historiography and Anti-Imperialism", titleAlt: "" },
      { time: 2210, title: "Leaving Laos, Moving Through Thailand and Singapore, and Running a Magazine", titleAlt: "" },
      { time: 2903, title: "Singapore, Lee Kuan Yew, and Political Disillusionment", titleAlt: "" },
      { time: 3596, title: "Malaysia, Hong Kong, and Regional Aftermath of Singapore Expulsion", titleAlt: "" },
      { time: 4608, title: "Postwar Vietnam Contacts and American Commercial Opening", titleAlt: "" },
      { time: 5350, title: "Unofficial Missions to Hanoi and Opening Vietnam’s Oil Sector", titleAlt: "" },
      { time: 6615, title: "Saigon Tourism, Mandarin Hotels, and Resort Development Efforts", titleAlt: "" },
      { time: 7122, title: "Arrest in Da Nang and Interrogation in Saigon", titleAlt: "" },
      { time: 7786, title: "Hong Kong, Illness, Divorce, and Personal Reckoning", titleAlt: "" },
      { time: 8378, title: "Publishing Crisis and the Opening of Shenzhen", titleAlt: "" },
      { time: 9238, title: "Ferrosilicon, Chinese Elite Networks, and Heavy Metals Trading", titleAlt: "" },
      { time: 10308, title: "Exit from Metals Trading and Digital Publishing Pivot", titleAlt: "" },
      { time: 11109, title: "Digitizing the Far Eastern Economic Review and Early Digital Publishing", titleAlt: "" },
      { time: 11460, title: "Beijing Office, Peking University, and English Training in China", titleAlt: "" },
      { time: 12280, title: "Founding a Mongolia Company and Moving to Mongolia", titleAlt: "" },
      { time: 13215, title: "Debt, Partnership, and the Mongolian Artisan Cheesemakers Union", titleAlt: "" },
      { time: 13711, title: "Personal Life and the Afterlife of Vietnam", titleAlt: "" },
    ],
  },
  "/ohms/interview42374.xml": {
    id: "interview42374",
    segmentCount: 17,
    segments: [
      { time: 0, title: "Introduction and Early Life", titleAlt: "" },
      { time: 337, title: "Japanese Occupation", titleAlt: "" },
      { time: 554, title: "Joining the army / nursing", titleAlt: "" },
      { time: 1265, title: "Working at the Japanese embassy", titleAlt: "" },
      { time: 1459, title: "Transition to Reuters", titleAlt: "" },
      { time: 1714, title: "Becoming a freelancer / Relationship with An", titleAlt: "" },
      { time: 2096, title: "Professional Relationship with Pham Xuan An", titleAlt: "" },
      { time: 2573, title: "Pham Xuan An's personality and communist suspicions", titleAlt: "" },
      { time: 2765, title: "Helping people as a paratrooper", titleAlt: "" },
      { time: 3043, title: "An leaving Reuters", titleAlt: "" },
      { time: 3403, title: "Meeting and working with Dick Swanson", titleAlt: "" },
      { time: 4170, title: "Reflections on covering the war", titleAlt: "" },
      { time: 4596, title: "Move to America and opening of restraurant", titleAlt: "" },
      { time: 5027, title: "Bringing family to America", titleAlt: "" },
      { time: 5412, title: "Pham Xuan An immediately post-war", titleAlt: "" },
      { time: 5969, title: "An's Spycraft", titleAlt: "" },
      { time: 6543, title: "Germaine's trips back to Vietnam", titleAlt: "" },
    ],
  },
  "/ohms/interview42707.xml": {
    id: "interview42707",
    segmentCount: 17,
    segments: [
      { time: 0, title: "Introduction", titleAlt: "" },
      { time: 26, title: "Early Life and Military Service", titleAlt: "" },
      { time: 291, title: "Early Journalism and Tenure at Time San Francisco", titleAlt: "" },
      { time: 572, title: "Tenure in Moscow and Transition to Bangkok / Opinions of the Vietnam War", titleAlt: "" },
      { time: 955, title: "Technical Difficulties", titleAlt: "" },
      { time: 1026, title: "Role of Bureau Chief in Bangkok", titleAlt: "" },
      { time: 1576, title: "Initial Meeting and First Impressions of Pham Xuan An", titleAlt: "" },
      { time: 2067, title: "Discussions of the War with An", titleAlt: "" },
      { time: 2601, title: "Impactful Stories and An's contribution", titleAlt: "" },
      { time: 2977, title: "An's Qualities / Discussion of World Memo", titleAlt: "" },
      { time: 3319, title: "Departure from Saigon and Work in Washington D.C.", titleAlt: "" },
      { time: 3524, title: "Reaction to News of An Being a Spy", titleAlt: "" },
      { time: 3855, title: "Visits to Vietnam", titleAlt: "" },
      { time: 4487, title: "An's Love for Vietnam / An's Family", titleAlt: "" },
      { time: 4949, title: "An's Trust in Others / Fundraising for An Pham", titleAlt: "" },
      { time: 5226, title: "Reflections and Concluding Thoughts on Vietnam and An", titleAlt: "" },
      { time: 5676, title: "Outro and Goodbyes", titleAlt: "" },
    ],
  },
};

/** Indexed segments across the whole collection. */
export const ohmsSegmentTotal = 113;
